server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cmfz
    password: 123
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .jsp
      prefix: /
    date-format: yyyy-MM-dd
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:com/baizhi/wbj/mapper/*DaoMapper.xml
  type-aliases-package: com.baizhi.wbj.entity
logging:
  level:
    com.baizhi.dao: debug